# Site settings
title: Mes parents se marient
author: Yann-Thomas LE MOIGNE
email: yann.tho.le.moigne@gmail.com
description: Mes parents se marient
baseurl: ""
url: "" # the base hostname & protocol for your site

facebook_username:
facebook_url:
ajl_mail:
ajl_phone:

# Build settings
markdown: kramdown
